[versions]
shadow = "7.1.2"
idea = "1.1.7"

vertx = "4.5.2"
junit = "5.9.1"
apache = "1.10.0"
docker = "3.3.4"

[libraries]
commons-text = { group = "org.apache.commons", name = "commons-text", version.ref = "apache" }

vertx-depchain = { group = "io.vertx", name = "vertx-stack-depchain", version.ref = "vertx" }
vertx-web = { group = "io.vertx", name = "vertx-web", version.ref = "vertx" }
vertx-json = { group = "io.vertx", name = "vertx-json-schema", version.ref = "vertx" }

vertx-junit = { group = "io.vertx", name = "vertx-junit5", version.ref = "vertx" }
junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }

docker = { group = "com.github.docker-java", name = "docker-java", version.ref = "docker" }
docker-http = { group = "com.github.docker-java", name = "docker-java.transport-httpclient5", version.ref = "docker" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "idea" }